<a href="https://colab.research.google.com/github/AmiMunshi/Data-compression-using-python/blob/master/Linear_Block_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
G= np.array([[1,0,0,1,0,1], [0,1,0,0,1,1], [0,0,1,1,1,0]]) #Generator Matrix
m= np.array([1,0,1]) # Data or message word

In [3]:
C= m.dot(G) % 2 #Code word is C=mG
print(C)

array([1, 0, 1, 0, 1, 1])

In [4]:
#Generating Codeword for all the possible data words
for i in range(2):
  for j in range(2):
    for k in range(2):
      m= np.array([i,j,k])
      C=m.dot(G)%2
      print(C)

     

[0 0 0 0 0 0]
[0 0 1 1 1 0]
[0 1 0 0 1 1]
[0 1 1 1 0 1]
[1 0 0 1 0 1]
[1 0 1 0 1 1]
[1 1 0 1 1 0]
[1 1 1 0 0 0]


In [6]:
P = G[:, 3:6]
print(P)

[[1 0 1]
 [0 1 1]
 [1 1 0]]


In [14]:
I= np.identity(3, dtype=int)

In [24]:
H= np.concatenate((P, I), axis=1)
print(H)

[[1 0 1 1 0 0]
 [0 1 1 0 1 0]
 [1 1 0 0 0 1]]


In [26]:
HT= H.T #Transpose of T
print(HT)

[[1 0 1]
 [0 1 1]
 [1 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


In [48]:
r= np.array([[1,1,0,0,1,0]])#Received Codeword
S= r.dot(HT)%2 #Calculate Syndrome
print(S)

[[1 0 0]]


In [50]:
#To find the location of the erroneous bit
ebit=np.where((HT == S).all(axis=1))
print("bit in error is: ",ebit[0])

bit in error is:  [3]


In [41]:
#Error Vector Table
e= np.identity(6, dtype=int)
print(e)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [43]:
#Extract Error Vector Corresponding to the Erroneous bit
evector= e[ebit[0],:]
print(evector)

[[0 0 0 1 0 0]]


In [51]:
#Corrected Codeword
c=(r+evector)%2
print("Corrected Codeword is ", c)

Corrected Codeword  [[1 1 0 1 1 0]]
